### ISSUE TITLE
Noob setup - Intelligent Octopus Go Time of Use Switch

### ISSUE THREAD

**Issue by TGRolando** [stevegal/solis_control#12]
Hi @stevegal,

This looks great and exactly what i'm looking for. I really don't want to go down the modbus route if i can avoid it.

I'm on Octopus Intelligent Go I have an automation set up so that when there is an Octopus Intelligent Slot "On" my Immersion Heater comes on, and then turns off when the slot is off.

I would like to apply this same logic to my Solis Inverter. My plan is to set the "Charge and Discharge" times to 00:01 to 23:59 and then turn the "Time of Use Switch" on the solis inverter on and off with the Octopus Intelligent Slot.

I've mainly used the UI to make changes and write automations so far, but now dipping me toe into the code side. It's hard! :)

So far I have installed pyscript:

![Screenshot 2024-01-06 at 13 19 09](https://github.com/stevegal/solis_control/assets/92257928/7dae19bd-5937-48e0-bb05-ea455d774c4c)

and i've copied the "solis_control_py" into the config/pyscript foder:

![Screenshot 2024-01-06 at 13 23 25](https://github.com/stevegal/solis_control/assets/92257928/71a36ac8-3a0b-4f98-88dd-9111e622c77b)

But this is where i'm now stuck. I know i'm meant to copy and paste your "service: pyscript.......", but i don't know where thats meant to go. Or what the next step after entering my API keys and details are.

Any guidance would be great, so thanks in advance! :)

**Comment by stevegal** [comment]
@TGRolando - yeah - it can be intimidating to start with, but don't worry - there's plenty of guidance to get you going with pyscript and homeassistant.

You'll need to edit your main "configuration.yaml"

in there you'll need something like
```
pyscript:
  allow_all_imports: true
  hass_is_global: true
  apps:
    solis_control:
      config:
```

and in that config section add your username etc...

this script exposes services, so you can invoke the solis controller via the api. Please make sure you look into the discharge/charge amps that are appropriate for your battery and inverter.

You can then go to the developer tools and call the service... or even create new scritps that call that service. Have fun and be careful!
