### ISSUE TITLE
Question: Agile Octopus - Battery Charging

### ISSUE THREAD

**Issue by brianhardy6** [stevegal/solis_control#13]
Hi,

This is not an issue, just a question.
I have managed to get your script working. Thanks for all your hard work on it.
I now have a basic script that I can manually run which calls the pyscript.solis_control service which sets the amps and charging slots.
I am a novice so I hope you don't mind the following question.
I would like to set a charging schedule triggered by low cost charging slots from BottlecapDave's Octopus integration.
Possible using ""octopus_energy_electricity_next_day_rates" as a trigger?
These values are fixed in the script:
service: pyscript.solis_control
data:
  days:
    - chargeCurrent: "60"
      dischargeCurrent: "60"
      chargeStartTime: "12:00"
      chargeEndTime: "15:30"
      dischargeStartTime: "00:00"
      dischargeEndTime: "00:00"
    - chargeCurrent: "60"
      dischargeCurrent: "60"
      chargeStartTime: "00:00"
      chargeEndTime: "00:00"
      dischargeStartTime: "00:00"
      dischargeEndTime: "00:00"
    - chargeCurrent: "60"
      dischargeCurrent: "60"
      chargeStartTime: "00:00"
      chargeEndTime: "00:00"
      dischargeStartTime: "00:00"
      dischargeEndTime: "00:00"

If I could somehow have a trigger that could input variable values?
I just don't know where to start - I have tried but I'm a bit lost if I'm honest.
Would you have any code or tips that you could share to help me achieve this?

Thanks

Brian

**Comment by stevegal** [comment]
Yeah, I do mine by creating a service using pyscript and use that to setup the inverter charge/discharge times (well, discharge times mainly for octopus saver session)

```
def saver_session_timer_factory(trigger_time, chargeDischarge):
    log.warning("chargeDischarge:"+str(chargeDischarge)+" trigger at:"+trigger_time)
    @time_trigger("once("+trigger_time+")")
    def call_charge():
        solis_charge(chargeDischarge)
    saver_session_setTimes.append(call_charge)

@service
async def saver_session_setup(event):
    log.warning(str(event))
    start = event['start']
    end = event['end']
    log.warning("saver session setup start "+start+ " end "+end)
    dateTimeStart = datetime.strptime(start,'%Y-%m-%d %H:%M')
    dateTimeEnd = datetime.strptime(end,'%Y-%m-%d %H:%M')
    dischargeStart = dateTimeStart.strftime('%H:%M')
    dischargeEnd = dateTimeEnd.strftime('%H:%M')
    trigger_time = (dateTimeStart - timedelta(hours=2)).strftime('%Y/%m/%d %H:%M:%S')
    log.warning("triggering at:"+trigger_time)
    saver_session_timer_factory(trigger_time, ["00:00","00:00", dischargeStart,dischargeEnd ])
```

is the kind of thing I use. You could easily set this up to be called and use your octopus integration to figure out the best times...

so you could do something like.. (in your automation)

```
alias: Automatically setup charge
description: setup charge times at cheapest rate
trigger:
  - platform: event
    event_type: octopus_energy_electricity_next_day_rates
condition: []
action:
  - service: pyscript.saver_session_setup
    data:
      event:
        rates: |
          {{ trigger.event }}
mode: single
```

assuming octopus_energy_electricity_next_day_rates is an event. If it's just data you could simply set a time trigger and get the python script to either use the data passed in or get the data itself... and sort etc. Should be okay, but you only get 3 charge/discharge slots, so you may need to setup a few time triggers. The python above kinda shows you how to get the python script to self trigger based of data if you need to make it a trigger based on the data. Hope that helps.
