### ISSUE TITLE
can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by lowpeter** [stevegal/solis_control#3]
Hi, Just got this ready, but got the following error. Unsure if this is the code, or something I done wrong. Could this be related to incorrect login info in the service call? tried both with and without " round the data. Hope you might have some advice.

Once this is working looking to make the service call smarter, like adding cheapest time from Octopus plugin and reading future Solar prediction. No idea how to do that, so will also be asking for more help.

Here is the error:

This error originated from a custom integration.

Logger: custom_components.pyscript.file.solis_control.solis_control
Source: custom_components/pyscript/eval.py:490
Integration: Pyscript Python scripting (documentation, issues)
First occurred: 12:47:31 (1 occurrences)
Last logged: 12:47:31

Exception in <file.solis_control.solis_control> line 87: body = '{"stationId":"'+config['plantId']+'"}' ^ TypeError: can only concatenate str (not "int") to str

**Comment by stevegal** [comment]
just wrap your plant id as a string...

so:
```plantId: "yourplantId" ``` in the configuration yaml and it should be fine

(you need to do the same for key_id as well)

**Comment by stevegal** [comment]
... and the usecase you describe is exactly how I use it

**Comment by lowpeter** [comment]
Thanks Stevegal. After pulling hair out I finally got it to work with manual service call. Just trying to figure out Octopus Target rate sensors. Would you be prepared to share any of your automation YAML or extra configurations?

last winter I was manually looking at the Octopus agile rates and then going into the Solis Cloud UI and updating the times to charge the battery a bit overnight. Also doing the same for a bit of charging around 3 in the afternoon before peak. It would be awesome to have Home assistant know the cheapest half hour and fillup the battery when the solar forcast was low - which was pretty much all winter!!

**Comment by stevegal** [comment]
shared in the other thread. I'm on the "GO" tarrif, so only one cheap rate for me, but I'm sure you can figure out how to adjust appropriatley and only one charge session time. Note the solis inverter only supports 3 charge/discharge time slots, so keep that in mind

**Comment by stevegal** [comment]
remember, you can use the automation triggers to do the service call for you. I have mine setup to call everyday at 23:00 so it's ready for the overnight charge window.

**Comment by stevegal** [comment]
@lowpeter - is it okay to close this issue now?

**Comment by lowpeter** [comment]
Yes, for sure. Sorry for not getting back. I think this is working now. Did not want to bombard you with questions immediately. Is there a place for discussion rather than issues?

Thank you so much for this.

**Comment by stevegal** [comment]
No problem. Just raise an issue and Iabel it as a discussion etc... I may take a while to respond as well.... day job.. kids etc...
