### ISSUE TITLE
Running this outside of HA?

### ISSUE THREAD

**Issue by mcqweb** [stevegal/solis_control#8]
I'm looking to run a simple script which grabs the next day's agile rates and sets the battery to charge from the grid depending on pricing. (And also manage the battery discharge rate when I'm charging the car, so that comes from the grid too).

I wonder how easy it would be to pick the core out of this so it could run standalone?

**Comment by stevegal** [comment]
the only thing you need is an alternative to from ` async_get_clientsession` - so should be really easy. 

However, home assistant will also give you agile rates from plugins there as well... and you could use this as a service to set the times. If you go the HA route as well, then others can easily benefit. Thinking to set up an automation to set your charge times based on agile the agile rates it already has would be okay.

**Comment by mcqweb** [comment]
Thanks - sorted it.

I completely take your point about using HA, and I'm sure I could do so much more with it however I'm conscious of the overhead and would rather, for now, run this as a userscript on Unraid.
